[package]
name = "primwrap"
version = "0.0.1"
authors = ["NightEule5 <24661563+NightEule5@users.noreply.github.com>"]
description = "Derive operation traits for primitive wrapper structs."
keywords = ["derive", "proc_macro", "wrappers"]
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
strum = { version = "0.25.0", features = ["derive"] }
syn = "2.0.38"
virtue = "0.0.15"

